name: Verify

on:
  workflow_call:
    inputs:
      node-versions:
        required: true
        type: string # A JSON string representing an array of Node.js versions to test against, e.g. '["18", "20", "24"]'

jobs:
  verify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ${{ fromJson(inputs.node-versions) }}

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - run: corepack enable
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm verify
